language: python
python:
    - "3.6"
install: python3 -m pipenv install --dev
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - psql -c 'create database "blogful-test";' -U postgres
script:
    - PYTHONPATH=. python3 tests/test_filters.py
    - PYTHONPATH=. python3 tests/test_views_integration.py
    - PYTHONPATH=. python3 tests/test_views_acceptance.py
    # Add any other tests here