"""empty message

Revision ID: bb713ac22fa0
Revises: 
Create Date: 2018-02-24 20:43:13.689504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb713ac22fa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('Entries', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Entries', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Entries', type_='foreignkey')
    op.drop_column('Entries', 'author_id')
    op.drop_table('users')
    # ### end Alembic commands ###
